disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Code Veteran"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "/logo.svg"
  secondaryLogo = "/logo.svg"
  description = "Code with wisdom, live with passion - Sharing both tech insights and life experiences"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "Code Veteran"
  email = "charellkingqu@gmail.com"
  image = "./image/favicon.png"
  imageQuality = 96
  headline = "Code with wisdom, live with passion."
  bio = "A little bit about you"
  links = [
    { email = "mailto:charellkingqu@gmail.com" },
    { discord = "https://discord.gg/fPWjkkgp" },
    { github = "https://github.com/CharellKing" },
    { linkedin = "https://www.linkedin.com/in/zhaojing-qu-574630258" },
  ]